python:
- '2.7'
before_install:
- gem install sass
install:
- pip install --user -r requirements.txt
script:
- python build.py build
after_success: |
  echo "$GITHUB_API_KEY"
  GH_REPO="@github.com/sebastianzillessen/datenwirken.de.git"
  if [ -n "$GITHUB_API_KEY" ]; then
    FULL_REPO="https://$GITHUB_API_KEY$GH_REPO"
    echo "Running deployment"
    git -c user.name='travis' -c user.email='travis' commit -am 'Travis Commit'
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push $FULL_REPO `git subtree split --prefix site master`:gh-pages --force
    # git push FU -f -q  gh-pages &2>/dev/null
  fi
env:
  global:
    secure: ucONvA2L5/0jm+lyifaNZXM6IFk+lSl/cANoboAP41ejMoJGe8HQ3Irs1K79ZxTOUYxzTM1QZjUQspq66w4xl/i/9/M0eRy9lVDCgKQ8W6O6jYJ8KK/xQYlLrEXHcXioBrSDZ9N9KQxjzOYopBP4BPDtQSsJLQc01Qy37xkxSSzy77Re8+xw1Em2YinlWSHnti2BiTzlvY504KKnpoKzZ7L9dAeC5+AQ+rnP6va86/OQhtiw4vsM+P9yeBCCqGsA26kULu7+kWitwRgQYmQgl094GP3OfKVzWMxuVIgoVYdITPmfXxyr3KYJyos48MaDQnA/VDL/twYwDQCaPzSRi24q5kn4FzC0ejh6ZiHz7c+eRXUfIKT5Ncyj0s5tcPdy6sxUSEGzltS4f7cX038NCDlb3CyirNtm929PXW3TXMhaOKmKu0gBdLJ2CEXm8PoUlOJkjA4qJGH9aJMKm0ifKRD0dQC8G2IE4xT9UGSrZUO5Vm6TsvO1ZrVZ12q5uZx1cUaJDuBfGoxGmmiEWUmwox0SjrreHovoWfEA3yg0EEtXWtOYBXgDpQIq6pOg64Xsc2s/JKcSJvQxIeP2mD66qJ6A7JeXmfLQDe4WqmAkXROfniHCeeEymiQOGitN9Ubgy3TIlBRR8CfRLqmt35bdoMgrbDFqCE2ZsJLfQUrroFE=
